services:
  - type: web
    name: news-app
    env: python
    buildCommand: pip install -r requirements.txt && python render_deploy.py
    startCommand: gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: postgresql://news_db_28y1_user:ECh5Rm8CZED6yJKvOPop1JPbmQNhM6fO@dpg-d6147m1r0fns73cbsiv0-a/news_db_28y1
        fromDatabase:
          name: news-db
          property: connectionString
      - key: ECh5Rm8CZED6yJKvOPop1JPbmQNhM6fO
        generateValue: true
      - key: NEWS_API_KEY
        fromSecret: news-api-key
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: media-storage
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1

databases:
  - name: news-db
    plan: free
    databaseName: news
    user: news

